### ISSUE TITLE
Mutliple trigger events from single Pinch Geusture

### ISSUE THREAD

**Issue by SabinMGeorge** [provencher/MRTK-Quest#100]
When interacting with the far pointer on UI buttons or MRTK buttons (in hand mode), single pinch action results in multiple OnClick events triggering. Is there anything I am doing wrong? Near interactions works fine as expected.

I am using Unity 2021.03.01f and the following submodules
Oculus Integration 28.0
Mixed Reality Toolkit v2.6
Oculus XR Plugin 1.8.1

**Comment by provencher** [comment]
Hi Sabin, I'd report this issue with MRTK, as it's an issue with their far pointer, rather than with the MRTK-Quest integration, which has not been tested with your setup, and is not actively supported.

https://github.com/microsoft/MixedRealityToolkit-Unity/issues
