### ISSUE TITLE
Objects Leave Hand When Head Moves 

### ISSUE THREAD

**Issue by jcellswo** [provencher/MRTK-Quest#103]
When you grab an object and move it toward or away from your face, it drifts out of your hand. We have posted [this issue](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10198) on the MRTK Github page but they have not responded. We've tried many Unity and MRTK versions, including the newest ones. It makes grabbing objects very inaccurate but doesn't appear to be a limitation of the accuracy of the hand-tracking itself...

**Comment by provencher** [comment]
Sorry your not getting answers there, though this is indeed an MRTK issue, not much I can help with on the MRTK-Quest front, sorry.
