### ISSUE TITLE
Hands visible but not working

### ISSUE THREAD

**Issue by lorak41** [provencher/MRTK-Quest#15]
Hi, I followed your instruction and FAQ, imported the scene but still hands are not able to interact with anything. What am I possibly missing?

**Comment by overvox** [comment]
I managed to make it partially work by making sure that the OVRPlugin and SDK are up-to-date.

At least one hand is working when Unity uses the following versions:

> Unity v2018.4.14f1, Oculus Utilities v1.45.0, OVRPlugin v1.45.0, SDK v1.1.30.0.

Before I updated everything after import via Oculus > Tools > Update OVR Utilities Plugin Unity logged the following versions, where I could only see the Controllers:

> Unity v2018.4.14f1, Oculus Utilities v1.45.0, OVRPlugin v1.38.0, SDK v1.1.22.0.


However, even though my hands are tracked only the right one is working and I while having consistent errors when interacting with objects.

> 02-10 14:57:22.591 17784 17802 I Unity   : Look rotation viewing vector is zero
02-10 14:57:22.591 17784 17802 I Unity   : UnityEngine.Quaternion:LookRotation_Injected(Vector3&, Vector3&, Quaternion&)
02-10 14:57:22.591 17784 17802 I Unity   : UnityEngine.Quaternion:LookRotation(Vector3, Vector3)
02-10 14:57:22.591 17784 17802 I Unity   : UnityEngine.Quaternion:LookRotation(Vector3)
02-10 14:57:22.591 17784 17802 I Unity   : Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:UpdateMousePointerEventData(PointerData) (at /Users/dimitrih/MaibornWolff/Repositories/MRTK-Quest copy/Assets/External/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:185)
02-10 14:57:22.591 17784 17802 I Unity   : Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:GetMousePointerEventData(Int32) (at /Users/dimitrih/MaibornWolff/Repositories/MRTK-Quest copy/Assets/External/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:168)
02-10 14:57:22.591 17784 17802 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/InputModules/StandaloneInputModule.cs:504)
02-10 14:57:22.591 17784 17802 I Unity   : Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:ProcessMrtkPointerLost(PointerData) (at /Use

and

> 02-10 14:57:22.591 17784 17802 E Unity   : Screen position out of view frustum (screen pos 64.000000, 64.000000, 1.000000) (Camera rect 0 0 128 128)
02-10 14:57:22.591 17784 17802 E Unity   : UnityEngine.Camera:ViewportToWorldPoint_Injected(Vector3&, MonoOrStereoscopicEye, Vector3&)
02-10 14:57:22.591 17784 17802 E Unity   : UnityEngine.Camera:ViewportToWorldPoint(Vector3, MonoOrStereoscopicEye)
02-10 14:57:22.591 17784 17802 E Unity   : UnityEngine.Camera:ViewportToWorldPoint(Vector3)
02-10 14:57:22.591 17784 17802 E Unity   : Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:UpdateMousePointerEventData(PointerData) (at /Users/dimitrih/MaibornWolff/Repositories/MRTK-Quest copy/Assets/External/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:218)
02-10 14:57:22.591 17784 17802 E Unity   : Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule:GetMousePointerEventData(Int32) (at /Users/dimitrih/MaibornWolff/Repositories/MRTK-Quest copy/Assets/External/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:168)
02-10 14:57:22.591 17784 17802 E Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/InputModules/StandaloneInputModule.cs:504)

**Comment by lorak41** [comment]
I solved my problem by using appropriate MRTK Quest profiles.
