### ISSUE TITLE
How to fix the keyboard interaction in the prvncherHandInteractionExamples2 scene cannot be used

### ISSUE THREAD

**Issue by heyangHEY** [provencher/MRTK-Quest#29]
why the keyboard cannot be called out after pressing the key？

**Comment by provencher** [comment]
Hi @heyangHEY. The keyboard triggered by that button is the touchscreen keyboard, which on HoloLens 2, triggers the system keyboard.

Quest does not have a system keyboard available to developers, so it cannot be used. 

As of MRTK v2.3, there is now a non-system keyboard that should work with Quest, but I haven’t gotten around to testing it. To make use of it, we’d need to integrate it into the test scene.

**Comment by provencher** [comment]
@heyangHEY this was solved in 0.6
