### ISSUE TITLE
Speech Input in Demo Scene

### ISSUE THREAD

**Issue by enes-oerdek** [provencher/MRTK-Quest#37]
First of all thanks for this great extension of MRTK. I love how easy it makes to use MRTK on Oculus Quest. It brings together the best of two worlds.

I am fairly new to all this. I'm currently doing some experiments with the Quest and testing out different input methods. MRTK also supports Speech Input. But for Oculus Quest I could not make it run. Since on the Readme "Full support for any interaction in the MRTK designed to work for HoloLens 2" is written, I was not sure whether I made something wrong, or whether it is currently still in work.
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Speech.html

I tested this on Oculus by deploying the testscene, but also by using Oculus Link and an external microphone. I saw that there are some voice commands on some buttons. But none of them seem to work. So the question is: How can I make speech input work?

**Comment by provencher** [comment]
@enesbil you’re right that speech doesn’t work on Quest. On HoloLens 2 this leverages Windows apis for dictation, which simply do not exist on Quest. They might however work on Rift if you re-add the speech provider in your profile. I have not tested that however.

Beyond that there aren’t any plans to properly support voice input. It changes too much from platform to platform.

**Comment by enes-oerdek** [comment]
Alright, thanks alot! :)
That explains why I could not make speech input run. I will test it out for Rift, if I am successful doing it, I will let you know. I think this issue has been resolved.
