### ISSUE TITLE
Support Avatar Hands emulating hand-tracking

### ISSUE THREAD

**Issue by provencher** [provencher/MRTK-Quest#4]
Add support for avatar hands when using controllers to emulate the use of hands, when using controllers.

**Comment by brendanluu** [comment]
Love this idea! Would be much faster if could still use controller as hand in editor!! Thank you for this

**Comment by provencher** [comment]
Adding information here about avatar hand hierarchy
![image](https://user-images.githubusercontent.com/7420990/73594643-345a8f00-44de-11ea-9a33-a7f506687802.png)

**Comment by provencher** [comment]
Progress update - Added support for initializing avatar hands.
Still working on getting hand joints properly setup.
