### ISSUE TITLE
Outline Can not be see in vr

### ISSUE THREAD

**Issue by NoviaDroid** [provencher/MRTK-Quest#49]
When running OutlineExamples scene in quest VR,the outline effect can not be seen in VR.

![image](https://user-images.githubusercontent.com/3263368/82182393-cf089d80-9916-11ea-94fa-fb1d30871e47.png)

**Comment by provencher** [comment]
Let me take a look at this!

**Comment by provencher** [comment]
@NoviaDroid this is an issue with rendering on Android, and doesn't have much to do this repo specifically. I'd recommend opening a bug report on official MRTK and tagging Cameron Micka.

Cheers,
Eric
