### ISSUE TITLE
Hand teleport can activate / trigger unexpectedly

### ISSUE THREAD

**Issue by machenmusik** [provencher/MRTK-Quest#61]
See https://github.com/provencher/MRTK-Quest/pull/60#issuecomment-642881249
and a little more detail in Slack
https://holodevelopers.slack.com/archives/CTW7K59U4/p1591902858020400?thread_ts=1591456024.474400&cid=CTW7K59U4

**Comment by provencher** [comment]
Should be solved with 1.0.1
