### ISSUE TITLE
Keep getting debug.LogError when hide/reload DcokExample objects group

### ISSUE THREAD

**Issue by Ericbing** [provencher/MRTK-Quest#63]
debug.LogError :
"AssertionException: Assertion failure. Value was Null
Expected: Value was not Null
When a dockable is docked, its dockedPosition must be valid.
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull (UnityEngine.Object value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
UnityEngine.Assertions.Assert.IsNotNull[T] (T value, System.String message) (at <23a7799da2e941b88c6db790c607d655>:0)
Microsoft.MixedReality.Toolkit.Experimental.UI.Dockable.Update () (at Assets/MRTK/SDK/Experimental/Dock/Dockable.cs:133)"

Way to recreate the issue: 

1. Add two buttons in MRTK-Quest_2.4_Extra scene.
Button one: Hide the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=off.
Button two: Show the DockExample object group in Hierarchy panel with "GameObject.SetActive" value=on.

2. Click button one to hide the DockExample object group, then click button two to show the group, then the debug.LogError will keep coming.

**Comment by provencher** [comment]
Hi thanks for logging this issue! I think you should file it under the official MRTK repo however. I don’t maintain the code in the framework, only the Quest compatibility layer.
