### ISSUE TITLE
When starting a scene with controllers,the avatar hands are not show until about 30 seconds delay

### ISSUE THREAD

**Issue by NoviaDroid** [provencher/MRTK-Quest#68]
If uncheck "renderAvatarHandsInsteadOfControllers" in MRTK-OculusConfig, the controller model can shown instantly when start scene. 

So why there is 30 seconds delay when show avatar hands? is it a oculus problem?

**Comment by NoviaDroid** [comment]
![image](https://user-images.githubusercontent.com/3263368/87032516-52f44d00-c217-11ea-9cab-91cc81fd37c6.png)
the delay is caused by AvatarSpecificationCallback in OvrAvatar.cs,seems to be an oculus issue

**Comment by provencher** [comment]
There's definitely a delay, but I don't think it's a full 30 seconds. That said, yeah there's nothing I can do about it.
