### ISSUE TITLE
Grabing only with middle finger

### ISSUE THREAD

**Issue by martdob** [provencher/MRTK-Quest#72]
The MRTK port to Oculus hand tracking is excellent!
Now, I would like to grab a weapon and shoot with the index finger.
Since the grabbing works with the index finger the shooting is not possible. 
I tried to modify QculusQuestHands.cs file. I was focusing on the   the section containing 

_isIndexGrabbing = HandPoseUtils.IsIndexGrabbing(ControllerHandedness);_
and 
_float indexFingerCurl = HandPoseUtils.IndexFingerCurl(ControllerHandedness);_

However, it did not work as expected. Have you got any other idea?

**Comment by provencher** [comment]
Hi @martdob. 

Here are the relevant things you have to modify

IsGrabbing is queried here in the event system
![image](https://user-images.githubusercontent.com/7420990/87985324-6326ea80-caa9-11ea-994b-233236b531d1.png)


Then you should be able to simply modify IsGrabbing here
![image](https://user-images.githubusercontent.com/7420990/87985371-7c2f9b80-caa9-11ea-9929-51101a687106.png)
