### ISSUE TITLE
Is this Project URP compatible?

### ISSUE THREAD

**Issue by castana1962** [provencher/MRTK-Quest#85]
Hi, I am very excited about using this project in my VR Health project. 
Since URP is very important to reduce the Calls and the FPS in the game.... 
For that reason, Is MRTK-Quest Project with Unity URP compatible?
or if it is not like that, Could I use in my own URP project and add the articulated hand tracking, and simulating hand tracking using controllers with avatar hands?
Thanks for your time
Best Regards
Alejandro
Ps. Sorry if it not the correct place to add this post but I did not know where ask this... :)

**Comment by Acimaz** [comment]
Yes it is. I managed to make it work under 2020.1 with URP. In my last post here I explain how you can activate it properly: https://github.com/provencher/MRTK-Quest/issues/84

**Comment by castana1962** [comment]
Hi Acimaz, Thanks for the info !!! Best Regards. Alejandro

**Comment by Acimaz** [comment]
You are welcome 👍

**Comment by provencher** [comment]
Thanks for linking your solution @Acimaz - MRTK does have an automatic updater for LWRP which I believe also works with URP.
If it works with MRTK and Android, it'll work with MRTK-Quest - nothing special about this project, except for the hands material which is a custom shader. 

The MRTK-OculusConfig scriptable object has a slot to change the material there, so feel free to replace it with a URP compatible material.
