### ISSUE TITLE
How to export the Hand Tracking Teleporting feature from this MRTK-Quest to my VR own project?

### ISSUE THREAD

**Issue by castana1962** [provencher/MRTK-Quest#86]
Hi Everyone.
I am building a Rehabilitation Treatments by VR Games( mainly for Oculus Quest for its mobility). I am very interested in adding the Hand Tracking Teleporting feature of this MRTK-Quest project to my own project (it would be great for that patient who has little mobility with their "hands" for your health problem and can move around the game by your hands. I guess that this feature is in the MRTK-Quest_2.4_Extra scene, for that reason, Would it be possible? Could anybody advise me about how to do it?
Thanks for your time
Regards
Alejandro
Ps. Maybe it is a little crazy idea but it's worth a try :)

**Comment by Acimaz** [comment]
Hello Castana,

yes, this is possible. I assume you already cloned the repo?

**Comment by castana1962** [comment]
Hi again
Yes, I did.
I guess that  MRTK-Quest_Development Scene is the correct one, right?
Could you say me what is the game object to the games object what I should export like unitypackage to add the Hand Tracking feature to my own VR project? or if you know some better way, please let me know it.
Thanks for your help
Regards
Alejandro

**Comment by Acimaz** [comment]
What i did was to first call the "createSymlink.sh" script inside the MRTK-Quest/Assets/External folder in your repo. Or when you are on windows the .bat. After that I copied the folders "Assets/MixedRealityToolkit.Generated", "MRTK", "MRTK.ThirdParty" and "Resources" over in my private project.

There may be another better way by symlinking stuff over to your private project or using git submodules but I think this is the easiest way.

**Comment by castana1962** [comment]
Hi Acimaz,
Sorry my ignorance and my little English :)
Should I execute the .bat file again? or if I have these folder in my Unity projects, Could I copy them to my own Unity project?
Thanks for your time
Alejandro

**Comment by Acimaz** [comment]
No problem, your english is good 👍 

If you executed the .bat already you can just copy these folders, yes. The .bat just creates a symbolic link from the External/MRTK folder to the Assets/MRTK folder.

**Comment by castana1962** [comment]
Thank you Acimaz !!!

**Comment by castana1962** [comment]
Hi Acimaz,
Good morning.
Sorry to bother you and my daring for this but I copied the folders that you told me and Unity "Crashed"╭( ◕﹏◕ )╮, for that reason, and since that your one works fine, Could you share it with me? I remember that this one is in URP, Would it be possible?
Thanks for your help
Regards
Alejandro

**Comment by Acimaz** [comment]
Hey Castana,

I can't do that with my main project because it's a project for our company (we are developing treatments for hand as well). However, I think I know what's causing the issue. In your copied MRTK folder, is there another MRTK folder which does not show up in unity? I had a similar issue because the symlink script created another symlink inside this MRTK folder which caused a recursive call of the same folder again and again. Of course, unity will crash after a while when doing so :D

**Comment by Acimaz** [comment]
![image](https://user-images.githubusercontent.com/3418387/91455856-e397f280-e882-11ea-9b82-354d60ef1248.png)

For me this folder had another folder called mrtk in it which was loading and loading. Just delete that and it should work fine. MRTK/MRTK folder.

**Comment by castana1962** [comment]
Hi Acimaz,
I will try it !!
Thanks
Alejandro

**Comment by provencher** [comment]
@castana1962 you don't need to clone this repo to make use of the features.

Follow the instructions for installing MRTK by Microsoft, and then install the unity packages in this release.
https://github.com/provencher/MRTK-Quest/releases/tag/v1.1.0

Alternatively, I have a sample project setup with everything and you can copy paste what you need from there.
https://github.com/provencher/MRTK-Quest-Sample

To note, the example scenes aren't special for the teleport feature, it's just a feature in the MRTK profile to enable teleport, and then MRTK-Quest will automatically enable it in your scene.

**Comment by castana1962** [comment]
Hi @provencher 
First, thanks for letting me get the MRTK-Quest-Sample.
Sorry for my ignorance, but my own Unity VR project uses Oculus Integration plugin to do the most VR Interactions. 
Although you told me that the teleport feature is not a special one on your MRTK project, What I should do to integrate only the Customized Teleport pointer for teleporting locomotion to hand tracking and touch controllers for Quest to my Unity/Oculus Integration project? 
Thanks for your time. 
Regards. 
Alejandro
Ps. Sorry for my little English :)

**Comment by provencher** [comment]
@castana1962 this is an MRTK extension that leverages the oculus sdk for basic input, and MRTK for interactions. 

I'm sorry to tell you that if you want to get rid of MRTK and just use Oculus integration I don't have an explanation to add the teleport feature, it's all very coupled and complicated.

Either you use MRTK and MRTK-Quest, and you have the teleport gesture, or you build your own teleport system, but I'm unfortunately not able to help with that. 

The code is all open source and you're free to take what you want from it, but I'm not about to right a version of the gesture that doesn't rely on MRTK.

Best of luck!

**Comment by castana1962** [comment]
Hi @provencher,  
Please, it is not my intention that you change your project or take out MRTK.
I only mentioned that mine is developing with a different VR plugin and adapt it from the Start to MRTK would be very complicated for me. I only asked you if it was possible to only take that hand tracking interactivity and if so, What would be the Game objects that I should integrate into my own project?
Thank you for allowing me to use your project to try and add a very important function for the benefit of people who have health problems and we are trying to help them with our project...
Best of luck to you too !!!
Regards
Alejandro
