### ISSUE TITLE
Connect with PUN2

### ISSUE THREAD

**Issue by MatiasBrunacci** [provencher/MRTK-Quest#95]
Just thinking louder here, but it would be soooo cool to have this running with PUN2 + Voice chat. 
This would mean a super functional VR multiplayer framework. 
Would you please consider adding this feature in the future?

**Comment by provencher** [comment]
Appreciate the feedback, though I won't be adding PUN support to this project. 

I might be updating this repo with Normcore support however. Right now it uses an older version of normcore and MRTK, but it should give you a baseline understanding for setting up multiplayer.
https://github.com/provencher/MRTK-Online

**Comment by provencher** [comment]
FYI I updated MRTK-Online this morning - give it a try!

**Comment by MatiasBrunacci** [comment]
@provencher OMG OMG OMG!! such a good news! I'll try it right away! thank you so much for doing this!
